### ISSUE TITLE
ABI breakage?

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [vasi/squashfuse#111]
Hi! 
I am updating the packaging for debian and I have run into some missing symbols. It seems https://github.com/vasi/squashfuse/commit/2ff837b814e84eedc25574014da9ed24ee44b7b4 has removed some functions directly related to these missing symbols. Are these public facing or internal? Thanks for any help you can provide.
Scarlett

**Comment by DrDaveD** [comment]
Please provide more details about exactly the error you see and give instructions on how to reproduce it.

**Comment by ScarlettGatelyMoore** [comment]
Hello, We use symbol files to track ABI changes between releases. 
https://wiki.debian.org/UsingSymbolsFiles
In your latest release, there are missig symbols without an SO version bump. Which can be fine if these are internal calls and not public facing. I need to know if this is the case with the following:
+#MISSING: 0.4.0-1# sqfs_cache_add@Base 0.0.0
+#MISSING: 0.4.0-1# sqfs_cache_invalidate@Base 0.0.0
+#MISSING: 0.4.0-1# sqfs_cache_add@Base 0.0.0
+#MISSING: 0.4.0-1# sqfs_cache_invalidate@Base 0.0.0

Thanks,
Scarlett

**Comment by vasi** [comment]
These symbols are intended to be internal, not public-facing.

Unfortunately we're mistakenly exporting the symbols, and shipping a header file that lists them. But these are not symbols that it makes any sense for another binary/library to use. See #65 for more discussion of the bad header file.

**Comment by ScarlettGatelyMoore** [comment]
Perfect. Thank you!
