### ISSUE TITLE
Compilation fails on Ubuntu Precise and CentOS 6

### ISSUE THREAD

**Issue by probonopd** [vasi/squashfuse#12]
Full build log [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/160005863/log.txt).

```
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether gcc and cc understand -c and -o together... yes
./configure: line 12055: SQ_PROG_CPP_POSIX_2001: command not found
./configure: line 12056: SQ_PROG_CC_WALL: command not found
./configure: line 12066: SQ_CHECK_DECL_MAKEDEV: command not found
./configure: line 12067: SQ_CHECK_DECL_PREAD: command not found
./configure: line 12068: SQ_CHECK_DECL_S_IFSOCK: command not found
./configure: line 12069: syntax error near unexpected token `:'
./configure: line 12069: `SQ_CHECK_DECL_ENOATTR(:)'
```

**Comment by probonopd** [comment]
Also running into this on CentOS 6.7 with EPEL.

**Comment by vasi** [comment]
That looks like autoconf failed to find our m4 files?

**Comment by probonopd** [comment]
Using [autotools-latest](https://www.softwarecollections.org/en/scls/praiskup/autotools/epel-6-x86_64/download/praiskup-autotools-epel-6-x86_64.noarch.rpm) seems to be a workaround.

Now running into `./configure: line 13091: syntax error near unexpected token 'pkgconfig_XZ,liblzma,'`. Deleting 2 instances of `PKG_CHECK_MODULES` in `configure` seems to be a workaround.

**Comment by Conan-Kudo** [comment]
@probonopd `squashfuse` builds fine on CentOS 6. It's even in EPEL today.

**Comment by vasi** [comment]
It looks like you have to install autoconf/automake/pkg-config before running autogen.sh.
