### ISSUE TITLE
Why is the compressed bit being set in inode headers when its size is 0?

### ISSUE THREAD

**Issue by mgord9518** [vasi/squashfuse#134]
I've been reading through SquashFS [documentation](https://www.kernel.org/doc/html/latest/filesystems/squashfs.html#inodes) and I've been unable to find anything indicating that the compressed bit should be set if the `size` is 0, what is the purpose of this code?

https://github.com/vasi/squashfuse/blob/94f998c58d2bb6dff00173f33140a0354adce324/fs.c#L137-L138

**Comment by vasi** [comment]
I don't know why it's not documented, but it's what the kernel does: https://github.com/torvalds/linux/blob/50dffbf771802c4db88de2cb942affa0ada43ad0/fs/squashfs/squashfs_fs.h#L108

**Comment by mgord9518** [comment]
@vasi I [asked](https://github.com/plougher/squashfs-tools/issues/58#issuecomment-2088700389) the author of SquashFS, apparently it only pertains to SquashFS 1.0 so it should be safe to remove

**Comment by vasi** [comment]
Oh nice, thanks for the followup.
