### ISSUE TITLE
can't configure on openWRT

### ISSUE THREAD

**Issue by tictaktoe333** [vasi/squashfuse#16]
I have installed all the prerequisites that I can find (openWRT uses OPKG not apt-get) and this is the part it gets stuck on:

> configure: checking for definition needed by ENOATTR
>checking if ENOATTR works without changes... no
>checking if ENOATTR requires changing _DARWIN_C_SOURCE... no
>checking if ENOATTR requires changing _NETBSD_SOURCE... no
>checking if ENOATTR requires changing _XOPEN_SOURCE... no
>checking if ENOATTR requires changing _BSD_SOURCE... no
>checking if ENOATTR requires changing _GNU_SOURCE... no
>checking if ENOATTR requires changing _POSIX_C_SOURCE... no
>checking for library containing uncompress... no
>checking for pkg-config... /usr/bin/pkg-config
>checking pkg-config is at least version 0.9.0... yes
>checking for pkgconfig_XZ... no
>checking for library containing lzma_stream_buffer_decode... no
>checking for library containing lzo1x_decompress_safe... no
>checking for library containing LZ4_decompress_safe... no
>configure: error: in `/root/downloads/squashfuse-master':
>configure: error: At least one decompression library must exist
>See `config.log' for more details

but I don't know the lzma files that ./configure is looking for, I don't know if the files are named differently for OPKG so it is not seeing it. I think the file it needs is
>/usr/lib/liblzma.so.5

or

>/usr/lib/liblzma.so.5.2.2
but the config.log said it needs a .pc file?

I have got squashfuse up and running on kali no problem but I have to install squashfuse on openWRT to mount a file in the filesystem

Any help would be much appreciated!

Thanks

**Comment by vasi** [comment]
Do you know what compression method your filesystem uses? You only need liblzma if you have an XZ compressed filesystem, but maybe it's gzip compressed instead.

Anyhow, squashfuse looks for liblzma in two ways:

1. It looks for a .pc file, if you have pkg-config installed.
2. It looks for liblzma.so . Note that it doesn't use a version suffix (eg: "liblzma.so.5"). Usually liblzma.so will just be a symlink to liblzma.so.5, so you can create that symlink if it's missing.

Of course, you also need the headers for liblzma.

**Comment by tictaktoe333** [comment]
Thanks for the clarification, I know it uses lzma as when I do binwalk on it, it shows me. I since got a refund on my GL-MT300A-ext because the reset button snapped on it, then I went with a AR150-ext as I managed to get that up and running in no time! Thanks for your help!
