### ISSUE TITLE
Add LZMA decompression support

### ISSUE THREAD

**Issue by ericdand** [vasi/squashfuse#17]
I have a SquashFS file that's compressed with LZMA, and I'd love to open it with squashfuse! ;)

**Comment by andyn** [comment]
Today I came across an eons-old squashfs image that I could not mount with due to the lack of LZMA support. I find it rather surprising that the feature hasn't yet been ported, because LZMA support for squashfs images obviously has existed for a long time.

**Comment by vasi** [comment]
It should be pretty easy to add, I just haven't encountered such an image in awhile. Would you like to give it a try?

**Comment by vido89** [comment]
+1 for adding LZMA decompression support

**Comment by vasi** [comment]
The "lzma" you're seeing is a bit confusing. That's for "liblzma", which does xz decompression. But we still don't quite support old-style "raw LZMA" compression.

Dup of PR #37
