### ISSUE TITLE
Document SQUASHFS_LREG_TYPE, SQUASHFS_LDIR_TYPE

### ISSUE THREAD

**Issue by probonopd** [vasi/squashfuse#19]
I have written [code that extracts squashfs](https://github.com/probonopd/AppImageKit/blob/19bd4c23a5e5e23786c2ad1f13666ee1e9117036/runtime.c#L226-L323). When trying to extract some (rare) files, I get:

```
TODO: Implement inode.base.inode_type 9
TODO: Implement inode.base.inode_type 8
```

According to [squashfs_fs.h]( https://github.com/vasi/squashfuse/blob/master/squashfs_fs.h), 

```
#define SQUASHFS_LDIR_TYPE		8
#define SQUASHFS_LREG_TYPE		9
```

Whatever that means. 

What are ldir, lreg? Something to do with sparse and xattr?

**Comment by vasi** [comment]
Thanks for using squashfuse. The different inode types are pretty internal, which is why they're undocumented.

The different L types are just longer forms. They're used when there's extra data that's uncommon, so it's not worth storing in the usual case. Eg: xattrs, or files with lengths over 32 bits, etc.

**Comment by probonopd** [comment]
Thanks @vasi 

The question is what would I have to change in my code to get rid of the placeholders so that instead of printing out 

```
TODO: Implement inode.base.inode_type 9
TODO: Implement inode.base.inode_type 8
```
it would actually work?

**Comment by vasi** [comment]
Probably just change your if statements to include the extra types:

```
} else if(inode.base.inode_type == SQUASHFS_REG_TYPE || inode.base.node_type == SQUASHFS_LREG_TYPE){
```

You might want to use a switch/case statement instead of an if, to make it easier to read.

**Comment by probonopd** [comment]
Thanks, it is working now.
