### ISSUE TITLE
RW support?

### ISSUE THREAD

**Issue by JonnyTech** [vasi/squashfuse#21]
Using this tool, is it possible to mount a squashfs file (an Android system image) in read-write mode so that I can modify its contents?

**Comment by probonopd** [comment]
squashfs is a read-only filesystem.

**Comment by probonopd** [comment]
`unsquashfs` then `mksquashfs` (both on another system, not while the system in question is running) would be my best bet.

**Comment by JonnyTech** [comment]
Already tried that but the resultant file does not work. Thanks for your help. I shall keep experimenting...
