### ISSUE TITLE
pkg-config not optional

### ISSUE THREAD

**Issue by vsoch** [vasi/squashfuse#32]
hey @vasi ! i'm building on ubuntu, and it looks like pkg-config is not optional (but required) at least per the building steps you outlined for ubuntu:

```bash
+ autoconf
configure.ac:39: error: possibly undefined macro: AC_MSG_FAILURE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
So the slight tweak to the install looks like this for me:

```bash
    apt-get update && apt-get install -y fuse libfuse2 git \
                      autoconf libtool make gcc pkg-config  \
                      libtool libfuse-dev liblzma-dev

    git clone https://github.com/vasi/squashfuse
    cd squashfuse
    libtoolize --force
    aclocal
    autoheader
    automake --force-missing --add-missing
    autoconf
    ./configure --with-xz=/usr/lib/
    make
```

Going to be trying it out soon! A random question for you - do you know any tricks to be able to host a squashfs on a server somewhere (FTP?) and the mount it from there? I want to be able to have (pretty large squased) datasets that containers can mount and am testing different ideas.

**Comment by vasi** [comment]
Hmm, should it be optional? It's nice to get pkg-config's m4 files

**Comment by vsoch** [comment]
Almost two years to respond to an issue (1 year 8 months) I've long passed over working on this, and although I wish you had responded sooner, it's under the bridge at this point. Thanks, closing issue.
