### ISSUE TITLE
make check on FreeBSD ran no tests

### ISSUE THREAD

**Issue by emaste** [vasi/squashfuse#41]
I built & tried to run tests (on FreeBSD-current) but get:
```
% make check
make  check-TESTS
============================================================================
Testsuite summary for squashfuse 0.1.103
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by vasi** [comment]
Ooh, thanks for trying! Do you have a config.log? That should help us figure out why tests aren't planned.

**Comment by vasi** [comment]
Did some quick testing, I think this branch should work: https://github.com/vasi/squashfuse/tree/vasi-fbsd

You'll need to make sure you have installed at least: autoconf automake libtool pkgconf fusefs-libs squashfs-tools coreutils. And also the sysctl `vfs.usermount=1`

Let me know how it goes!

**Comment by vasi** [comment]
Fixed on master!

**Comment by emaste** [comment]
Oh no, somehow I missed this discussion two years ago. Thank you for fixing this!
