### ISSUE TITLE
Is it possible to use relative paths?

### ISSUE THREAD

**Issue by john-cena-141** [vasi/squashfuse#45]
Hello, sorry if this is stupid, 
I'm trying to run squashfuse on relative path. The absolute path is working but I need it to be relative.
When running on relative it's not detecting the .squashfs file at all.

**Comment by probonopd** [comment]
Please post an example to reproduce.

**Comment by john-cena-141** [comment]
I want to compress a game.

I made a separate directory for squash. squash/squashfuse is a file that I can use as replacement for having squashfuse installed, it works when using absolute path. /share/data is the mounting location.

A friend said to use this command inside the start.sh file.
```
cd "`dirname "$0"`"/Torchlight
squash/squashfuse squash/data.squashfs /share/data
```

The log shows:
```
./start.sh: line 9: cd: ./Torchlight: No such file or directory
./start.sh: line 10: /squash/squashfuse: No such file or directory
```

**Comment by vasi** [comment]
This is a problem with your script, it looks like the first line (which doesn't even mention squashfuse) isn't correct given your current directory. Squashfuse definitely works with relative paths.

Sorry! Hope your friend can help you debug your script.
