### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by haampie** [vasi/squashfuse#50]
Can we get a new tagged release? It's been roughly 3 years and there have been ~50 new commits since. Package managers like to use a tagged release.

**Comment by haampie** [comment]
In particular libfuse3 support is not part of a tagged version right now.

**Comment by chipturner** [comment]
Sure, I can cut a new release this week.

**Comment by haampie** [comment]
Great!

**Comment by chipturner** [comment]
done

**Comment by haampie** [comment]
@chipturner v0.1.104 is missing a download with just the configure script. See the difference between

https://github.com/vasi/squashfuse/releases/tag/0.1.104 and https://github.com/vasi/squashfuse/releases/tag/0.1.103

Could that be added?

**Comment by chipturner** [comment]
Done, sorry, been a while since I made a release.  I've uploaded a couple of archives that look correct.  Let me know if you experience other issues.

**Comment by haampie** [comment]
Works fine for me :) i've updated the spack recipe https://github.com/spack/spack/pull/22605
