### ISSUE TITLE
squashfuse_ll as a library

### ISSUE THREAD

**Issue by haampie** [vasi/squashfuse#51]
There is a Debian package called libsquashfuse0 which carries this patch around:

https://salsa.debian.org/sgmoore/squashfuse/-/blob/master/debian/patches/install_squashfuse_lowlevel.patch

which was used by the appimage team to allow static linking against squashfuse_ll.a instead of calling an executable.

The changes come down to renaming `main` to `fuse_main` and changing the executable into a library. Would it be a good idea to split the current ll.c into two source files so that we can have both squashfuse_ll and squashfuse_ll.{a,.so}?

**Comment by chipturner** [comment]
Those patches don't apply cleanly.  If you want to send a PR that moves to fuse_main and provides a library, but still also provides an executable, happy to merge it.
