### ISSUE TITLE
Support libfuse2 and libfuse3 at the same time with dlopen?

### ISSUE THREAD

**Issue by haampie** [vasi/squashfuse#60]
Now that squashfuse_ll.a is a library on its own, it can be used to create self-mounting squashfs executables (e.g. appimage / xar). When distributing those, the problem is we don't know whether the target machine has libfuse2 or 3, and right now that is fixed at compile-time.

Can we use dlopen to figure this out at runtime instead?

**Comment by probonopd** [comment]
> Now that squashfuse_ll.a is a library on its own, it can be used to create self-mounting squashfs executables (e.g. appimage / xar).

Is there an example somewhere for how to do that?

**Comment by haampie** [comment]
I haven't done that yet, you can use the squashfuse_ll.pc package config file to get the ll.h header & libsquashfuse_ll.{a,so} lib, and then copy the bits you need from `ll_main.c` to your own project.

**Comment by chipturner** [comment]
I would suggest finding some other FUSE filesystem that does fuse2/fuse3 at runtime.  It seems like it would probably be an invasive (perhaps impossible, given data structure changes).  But maybe it's possible and someone has done it.  But I don't want to be first :)

**Comment by haampie** [comment]
Ok, that's understandable. I think I'll just happily link against a particular version of libfuse instead of dlopening anyways.

**Comment by haampie** [comment]
The issue is licensing; libfuse is LGPL which means

> If you statically link against an LGPLed library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.

This can be problematic for users

**Comment by haampie** [comment]
Hm, statically linking libfuse is not a good idea because the path to the setuid binary fusermount (FUSERMOUNT_DIR) is set compile-time, so it wouldn't be portable. Shared linking is more portable.

**Comment by chipturner** [comment]
I am concerned all of these options add a bit of complexity for fairly niche use case.  What systems only have libfuse2?  libfuse3 is four years old and the last release of libfuse2 was Jan 2019.

**Comment by haampie** [comment]
Probably @probonopd can correct me, but appimagekit is rather conservative with dependencies (compiling against old libc etc) so that they can distribute one binary that works everywhere assuming abi compatibility. To support old systems they dlopen libfuse2, but now there are new distro's that might not have libfuse2 installed anymore, so they might need to add a hack to support both. I guess libfuse is their only dep that is breaking abi
