### ISSUE TITLE
multi-threaded FUSE loop?

### ISSUE THREAD

**Issue by reidpr** [vasi/squashfuse#66]
[Line 146 of `ll_main.c`](https://github.com/vasi/squashfuse/blob/74f4fe86ebd47a2fb7df5cb60d452354f977c72e/ll_main.c#L146) currently uses the single-threaded [`fuse_session_loop()`](https://libfuse.github.io/doxygen/include_2fuse__lowlevel_8h.html#a5f1e538aa3287e251afbe985438c4249).

libfuse3 seems to have a multi-threaded version [`fuse_session_loop_mt()`](https://libfuse.github.io/doxygen/include_2fuse__lowlevel_8h.html#abf73f7cd9149b60f9635b8eac429fb1f), and there is a "FIXME: multithreading" comment on line 145.

Is there anything blocking use of the multi-threaded loop? I ask because we are using SquashFUSE as a library and it would be simple to just call `fuse_session_loop_mt()` instead. I hesitate to do this though because I'm guessing there's a good reason SquashFUSE doesn't.

Or have I misunderstood something?

Thanks for your hard work on SquashFUSE. It's very valuable to us.

**Comment by DrDaveD** [comment]
There's a fix for that in #70.
