### ISSUE TITLE
Support zstd (Zstandard) compression

### ISSUE THREAD

**Issue by JessiAuro** [vasi/squashfuse#67]
Pretty much every other SquashFS implementation supports zstd compression (squashfs-tools, squashfs-tools-ng, kernel driver) so it would be nice to have it in the FUSE implementation too.

**Comment by vasi** [comment]
It's already there! https://github.com/vasi/squashfuse/blob/master/decompress.c#L103

Is your distro possibly building without zstd support? You could make a request to the packager.

**Comment by JessiAuro** [comment]
Oh! Nice. The readme makes no mention of it under the supported compression algorithms so didn't bother trying to mount something using zstd. 😅

I guess the issue is that the docs need updating.

**Comment by vasi** [comment]
Ah good point! Fixed :)
