### ISSUE TITLE
Can't find FUSE with pkgconfig

### ISSUE THREAD

**Issue by azubieta** [vasi/squashfuse#69]
The configuration tool complains about missing FUSE while there is evidence in the logs that it was already found above. Notice that I'm trying to use a fuse build installed in a non standard location.

```
PKG_CONFIG_PATH=../../../deps-prefix/lib/pkgconfig ../squashfuse/configure
....

checking for pkgconfig_fuse... yes
checking for FUSE library... no
configure: error: in `/home/alexis/Workspace/AppImage/appimage-runtime/cmake-build-debug/squashfuse-prefix/src/squashfuse-build':
configure: error: Can't find FUSE with pkgconfig
```

**Comment by probonopd** [comment]
Hence, I entirely avoid pkgconfig :)

These tools are all more guesswork than anything.
This works for me: https://github.com/probonopd/static-tools/blob/master/src/runtime/Makefile

**Comment by azubieta** [comment]
@probonopd Notice that you're using the system fuse files in your code. My issue is when fuse is not installed.

**Comment by azubieta** [comment]
Found a workaround setting the `PKG_CONFIG_PATH` also for `autogen.sh`.

This may be a bug on autotools.
