### ISSUE TITLE
version 0.1.105 is missing release tarball

### ISSUE THREAD

**Issue by haampie** [vasi/squashfuse#74]
There's no download for a release tarball https://github.com/vasi/squashfuse/releases/download/0.1.105/squashfuse-0.1.105.tar.gz

**Comment by chenrui333** [comment]
cc @vasi

**Comment by chenrui333** [comment]
Any update?

**Comment by haampie** [comment]
bump

**Comment by DrDaveD** [comment]
I'm not sure where those extra release assets came from before version 0.1.105, but I don't think the tarball is necessary because the standard github archive URL works:

https://github.com/vasi/squashfuse/archive/0.1.105/squashfuse-0.1.105.tar.gz

**Comment by haampie** [comment]
Hi @DrDaveD, there are two issues with the Github archive URL:

1. It does not have a stable checksum, the archive is created dynamically on request. This is a problem for packagers who want to do checksum validation. This has caused issues [in the past](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/) and as far as I know, GitHub still does not guarantee stable checksums.

2. The archive doesn't contain a generated configure script, meaning that `libtool`, `automake` and `autoconf` are required build dependencies. Typically autotools packages provide a release tarball with the configure script included.

Can you reopen this issue?

**Comment by vasi** [comment]
Yeah, we can run `make dist` to get a release tarball. Probably there's a way to convince github actions to produce this automatically for a release.

**Comment by DrDaveD** [comment]
Ok I did a manual `make dist` and attached the tarball to the 0.2.0 release, and #92 will make it happen automatically from now on.
