### ISSUE TITLE
Progress stalled on this important software

### ISSUE THREAD

**Issue by DrDaveD** [vasi/squashfuse#84]
It's been a long time since there has been any action on the pull requests in this repository.  Is there anything I can do to help?  I volunteer to be a co-maintainer, or to take primary responsibility for it, if that helps.  It is a vital part of [Apptainer](https://github.com/apptainer/apptainer) now, a project supported by the Linux Foundation.  We would be happy to give squashfuse a home under https://github.com/apptainer if @vasi is willing to transfer it.

**Comment by vasi** [comment]
Hey, thanks for the reminder. You're right, I haven't really had time to monitor this much. I'd gladly add maintainers, as you can see I've already done that before with chipturner. My main constraint is that I'd like squashfuse to continue to work well on many OSes, not just Linux. Sound ok to you?

If you don't mind, I'd rather not move this under the Apptainer namespace, though.

**Comment by DrDaveD** [comment]
Ok that sounds fine.  I'd be happy to help as a maintainer.  Let me know if there are any other rules you would like me to follow.
